In [ ]:
# Khái báo thư viện
import numpy as np
import pandas as pd
import matplotlib as plt
print("Khai báo thư viện thành công")

In [16]:
#Nhập dữ liệu từ ổ cứng
data = pd.read_csv('subset-covid-data.csv', header=0, encoding = "ISO-8859-1")  

data

,country,continent,date,day,month,year,cases,deaths,country_code,population
0,Afghanistan,Asia,2020-04-12,12,4,2020,34,3,AFG,37172386.0
1,Albania,Europe,2020-04-12,12,4,2020,17,0,ALB,2866376.0
2,Algeria,Africa,2020-04-12,12,4,2020,64,19,DZA,42228429.0
3,Andorra,Europe,2020-04-12,12,4,2020,21,2,AND,77006.0
4,Angola,Africa,2020-04-12,12,4,2020,0,0,AGO,30809762.0
...,...,...,...,...,...,...,...,...,...,...
201,Venezuela,America,2020-04-12,12,4,2020,0,0,VEN,28870195.0
202,Vietnam,Asia,2020-04-12,12,4,2020,4,0,VNM,95540395.0
203,Yemen,Asia,2020-04-12,12,4,2020,0,0,YEM,28498687.0
204,Zambia,Africa,2020-04-12,12,4,2020,0,0,ZMB,17351822.0
205,Zimbabwe,Africa,2020-04-12,12,4,2020,3,0,ZWE,14439018.0

In [17]:
# Số lượng dòng và cột của bộ dữ liệu
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       206 non-null    object
 1   continent     206 non-null    object
 2   date          206 non-null    object
 3   day           206 non-null    int64
 4   month         206 non-null    int64
 5   year          206 non-null    int64
 6   cases         206 non-null    int64
 7   deaths        206 non-null    int64
 8   country_code  202 non-null    object
 9   population    202 non-null    float64
dtypes: float64(1), int64(5), object(4)
memory usage: 16.2+ KB

In [18]:
# Tìm hiểu xem dữ liệu được thống kê cho những ngày nào
data.date.value_counts()

2020-04-12    204
2020-01-18      1
2020-04-11      1
Name: date, dtype: int64

In [21]:
data.head(2)

,country,continent,date,day,month,year,cases,deaths,country_code,population
0,Afghanistan,Asia,2020-04-12,12,4,2020,34,3,AFG,37172386.0
1,Albania,Europe,2020-04-12,12,4,2020,17,0,ALB,2866376.0

In [28]:
# lọc dữ liệu nhiễu:
cleaned_data = data[data.cases == 0]
cleaned_data

,country,continent,date,day,month,year,cases,deaths,country_code,population
4,Angola,Africa,2020-04-12,12,4,2020,0,0,AGO,30809762.0
5,Anguilla,America,2020-04-12,12,4,2020,0,0,NaN,NaN
6,Antigua_and_Barbuda,America,2020-04-12,12,4,2020,0,0,ATG,96286.0
20,Benin,Africa,2020-04-12,12,4,2020,0,0,BEN,11485048.0
22,Bhutan,Asia,2020-04-12,12,4,2020,0,0,BTN,754394.0
24,"Bonaire, Saint Eustatius and Saba",America,2020-04-12,12,4,2020,0,0,NaN,NaN
26,Botswana,Africa,2020-04-12,12,4,2020,0,0,BWA,2254126.0
28,British_Virgin_Islands,America,2020-04-12,12,4,2020,0,0,VGB,29802.0
29,Brunei_Darussalam,Asia,2020-04-12,12,4,2020,0,0,BRN,428962.0
37,Cases_on_an_international_conveyance_Japan,Other,2020-01-18,18,1,2020,0,0,NaN,3000.0
39,Central_African_Republic,Africa,2020-04-12,12,4,2020,0,0,CAF,4666377.0
40,Chad,Africa,2020-04-12,12,4,2020,0,0,TCD,15477751.0
44,Congo,Africa,2020-04-12,12,4,2020,0,0,COG,5244363.0
49,CuraÃÂ§ao,America,2020-04-12,12,4,2020,0,0,CUW,159849.0
55,Dominica,America,2020-04-12,12,4,2020,0,0,DMA,71625.0
59,El_Salvador,America,2020-04-12,12,4,2020,0,0,SLV,6420744.0
60,Equatorial_Guinea,Africa,2020-04-12,12,4,2020,0,0,GNQ,1308974.0
61,Eritrea,Africa,2020-04-12,12,4,2020,0,0,ERI,NaN
65,Falkland_Islands_(Malvinas),America,2020-04-12,12,4,2020,0,0,NaN,NaN
66,Faroe_Islands,Europe,2020-04-12,12,4,2020,0,0,FRO,48497.0
67,Fiji,Oceania,2020-04-12,12,4,2020,0,0,FJI,883483.0
70,French_Polynesia,Oceania,2020-04-12,12,4,2020,0,0,PYF,277679.0
78,Greenland,America,2020-04-12,12,4,2020,0,0,GRL,56025.0
79,Grenada,America,2020-04-12,12,4,2020,0,0,GRD,111454.0
87,Holy_See,Europe,2020-04-12,12,4,2020,0,0,VAT,1000.0
101,Jersey,Europe,2020-04-12,12,4,2020,0,0,JEY,106800.0
113,Liechtenstein,Europe,2020-04-12,12,4,2020,0,0,LIE,37910.0
116,Madagascar,Africa,2020-04-12,12,4,2020,0,0,MDG,26262368.0
119,Maldives,Asia,2020-04-12,12,4,2020,0,0,MDV,515696.0
122,Mauritania,Africa,2020-04-12,12,4,2020,0,0,MRT,4403319.0
127,Mongolia,Asia,2020-04-12,12,4,2020,0,0,MNG,3170208.0
129,Montserrat,America,2020-04-12,12,4,2020,0,0,MSR,5900.0
131,Mozambique,Africa,2020-04-12,12,4,2020,0,0,MOZ,29495962.0
133,Namibia,Africa,2020-04-12,12,4,2020,0,0,NAM,2448255.0
134,Nepal,Asia,2020-04-12,12,4,2020,0,0,NPL,28087871.0
136,New_Caledonia,Oceania,2020-04-12,12,4,2020,0,0,NCL,284060.0
138,Nicaragua,America,2020-04-12,12,4,2020,0,0,NIC,6465513.0
142,Northern_Mariana_Islands,Oceania,2020-04-12,12,4,2020,0,0,MNP,56882.0
148,Papua_New_Guinea,Oceania,2020-04-12,12,4,2020,0,0,PNG,8606316.0
159,Saint_Kitts_and_Nevis,America,2020-04-12,12,4,2020,0,0,KNA,52441.0
160,Saint_Lucia,America,2020-04-12,12,4,2020,0,0,LCA,181889.0
161,Saint_Vincent_and_the_Grenadines,America,2020-04-12,12,4,2020,0,0,VCT,110210.0
163,Sao_Tome_and_Principe,Africa,2020-04-12,12,4,2020,0,0,STP,211028.0
167,Seychelles,Africa,2020-04-12,12,4,2020,0,0,SYC,96762.0
170,Sint_Maarten,America,2020-04-12,12,4,2020,0,0,SXM,41486.0
173,Somalia,Africa,2020-04-12,12,4,2020,0,0,SOM,15008154.0
180,Suriname,America,2020-04-12,12,4,2020,0,0,SUR,575991.0
186,Timor_Leste,Asia,2020-04-12,12,4,2020,0,0,TLS,1267972.0
187,Togo,Africa,2020-04-12,12,4,2020,0,0,TGO,7889094.0
191,Turks_and_Caicos_islands,America,2020-04-12,12,4,2020,0,0,TCA,31458.0
192,Uganda,Africa,2020-04-12,12,4,2020,0,0,UGA,42723139.0
196,United_Republic_of_Tanzania,Africa,2020-04-12,12,4,2020,0,0,TZA,56318348.0
201,Venezuela,America,2020-04-12,12,4,2020,0,0,VEN,28870195.0
203,Yemen,Asia,2020-04-12,12,4,2020,0,0,YEM,28498687.0
204,Zambia,Africa,2020-04-12,12,4,2020,0,0,ZMB,17351822.0